FROM alpine:3.18

RUN apk add --no-cache \
    ansible \
    openssh \
    sshpass \
    python3 \
    py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install ansible-core \
    && ansible-galaxy collection install community.general

# Create SSH directory
RUN mkdir -p /root/.ssh && \
    chmod 700 /root/.ssh

WORKDIR /etc/ansible

ENTRYPOINT ["sh", "-c", "if [ ! -f /root/.ssh/id_rsa ]; then ssh-keygen -q -t rsa -N '' -f /root/.ssh/id_rsa; fi && /bin/sh"]